name: http_network
description: Project for handle request to http
version: 0.0.2
homepage: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
